// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFbdfhiz2IvSQpfWthKsdNKFvz998z9UY',
    appId: '1:1003600553489:web:1a4c586344871ca37373b0',
    messagingSenderId: '1003600553489',
    projectId: 'testphoneauth-af299',
    authDomain: 'testphoneauth-af299.firebaseapp.com',
    storageBucket: 'testphoneauth-af299.appspot.com',
    measurementId: 'G-SWTWRKVPY5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlbcw6dSvnNIPvjjx93zWDdIEJIbRBi1U',
    appId: '1:1003600553489:android:e279223cbedf63727373b0',
    messagingSenderId: '1003600553489',
    projectId: 'testphoneauth-af299',
    storageBucket: 'testphoneauth-af299.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDn-j1Blbssovwe5mWhpqxNtiVO1WQ2EmA',
    appId: '1:1003600553489:ios:1c0b8d8f9738724f7373b0',
    messagingSenderId: '1003600553489',
    projectId: 'testphoneauth-af299',
    storageBucket: 'testphoneauth-af299.appspot.com',
    iosBundleId: 'com.example.taskApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDn-j1Blbssovwe5mWhpqxNtiVO1WQ2EmA',
    appId: '1:1003600553489:ios:1c0b8d8f9738724f7373b0',
    messagingSenderId: '1003600553489',
    projectId: 'testphoneauth-af299',
    storageBucket: 'testphoneauth-af299.appspot.com',
    iosBundleId: 'com.example.taskApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAFbdfhiz2IvSQpfWthKsdNKFvz998z9UY',
    appId: '1:1003600553489:web:fa74822f17ac1a797373b0',
    messagingSenderId: '1003600553489',
    projectId: 'testphoneauth-af299',
    authDomain: 'testphoneauth-af299.firebaseapp.com',
    storageBucket: 'testphoneauth-af299.appspot.com',
    measurementId: 'G-DSJ46DPZQX',
  );

}